CREATE TABLE "public"."contact_infos" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "member_id" uuid,
  "application_id" uuid,
  "client_id" uuid,
  "email" text,
  "discord" text,
  "telegram" text,
  "twitter" text,
  "github" text,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON UPDATE restrict ON DELETE restrict,
  FOREIGN KEY ("application_id") REFERENCES "public"."applications"("id") ON UPDATE restrict ON DELETE restrict,
  FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON UPDATE restrict ON DELETE restrict,
  UNIQUE ("id"),
  UNIQUE ("email"),
  UNIQUE ("discord"),
  UNIQUE ("telegram"),
  UNIQUE ("twitter"),
  UNIQUE ("github")
);
