const designOptions = {
  design_sprint: {
    title: "Design Sprint (5 day / 3 day)",
    description: "",
    hours: 50,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 7,
    active: false,
  },
  design_research: {
    title: "Design Research",
    description: "",
    hours: 20,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 2,
    active: false,
  },
  user_stories: {
    title: "User Story Mapping / User Flows",
    description: "",
    hours: 20,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 2,
    active: false,
  },
  information_architecture: {
    title: "Information Architecture / Sitemap",
    description: "",
    hours: 10,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 0,
    active: false,
  },
  wireframes: {
    title: "Low-fidelity Wireframes",
    description: "",
    hours: 20,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 2,
    active: false,
  },
  mockups: {
    title: "High-fidelity Mock-up",
    description: "",
    hours: 60,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 4,
    active: false,
  },
  prototype: {
    title: "Clickable Prototype",
    description: "",
    hours: 20,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 0,
    active: false,
  },
  design_system: {
    title: "UI Components Library / Design System",
    description: "",
    hours: 40,
    hourly: 100,
    min_timeline: 4,
    max_timeline: 6,
    active: false,
  },
  user_testing_basic: {
    title: "User Testing / Validation (Basic)",
    description: "",
    hours: 60,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 4,
    active: false,
  },
  user_testing_advanced: {
    title: "User Testing / Validation (Advanced)",
    description: "",
    hours: 100,
    hourly: 100,
    min_timeline: 4,
    max_timeline: 6,
    active: false,
  },
  marketing_website: {
    title: "Marketing Website",
    description: "",
    hours: 40,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 3,
    active: false,
  },
  logo_style_guide: {
    title: "Logo and Style Guide",
    description: "",
    hours: 40,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 3,
    active: false,
  },
  brand_book: {
    title: "Brand Book",
    description: "",
    hours: 100,
    hourly: 100,
    min_timeline: 4,
    max_timeline: 6,
    active: false,
  },
  illustrations: {
    title: "Graphic design / Illustrations",
    description: "",
    hours: 20,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 2,
    active: false,
  },
};

export default designOptions;
