const developmentOptions = {
  light_web3: {
    title: "Light web3 Interactions",
    description: "single page, 1-2 method calls and event listening",
    hours: 50,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 4,
    active: false,
  },
  ui_light_web3: {
    title: "UI intensive but light web3 Interactions",
    description: "heavy layout and user experienc, lots of visualizations",
    hours: 80,
    hourly: 100,
    min_timeline: 6,
    max_timeline: 8,
    active: false,
  },
  heavy_web3: {
    title: "Heavy web3 interactions",
    description: "multiple pages, 3+ web3 calls, visualizations",
    hours: 150,
    hourly: 100,
    min_timeline: 10,
    max_timeline: 0,
    active: false,
  },
  smart_contract: {
    title: "Single Smart Contract",
    description: "",
    hours: 100,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 5,
    active: false,
  },
  multiple_smart_contracts: {
    title: "Multiple Smart Contracts",
    description: "",
    hours: 300,
    hourly: 100,
    min_timeline: 7,
    max_timeline: 0,
    active: false,
  },
  need_audit: {
    title: "Needs Audit",
    description: "",
    hours: 300,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 0,
    active: false,
  },
  no_code_backend: {
    title: "No Code Backend",
    description: "",
    hours: 30,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 4,
    active: false,
  },
  db_backend: {
    title: "Database & Backend Framework",
    description: "",
    hours: 200,
    hourly: 100,
    min_timeline: 6,
    max_timeline: 8,
    active: false,
  },
  fiat_integration: {
    title: "Fiat Integration",
    description: "",
    hours: 100,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 4,
    active: false,
  },
  subgraph: {
    title: "Subgraph",
    description: "",
    hours: 50,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 4,
    active: false,
  },
};

export default developmentOptions;
