const specificationOptions = {
  detailed_spec: {
    title: "Detailed Specification",
    description: "",
    hours: 10,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 2,
    active: false,
  },
  simple_token: {
    title: "Simple Token & Incentive",
    description: "",
    hours: 30,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 5,
    active: false,
  },
  decent_token: {
    title: "Decent Token & Incentive",
    description: "",
    hours: 65,
    hourly: 100,
    min_timeline: 5,
    max_timeline: 7,
    active: false,
  },
  complex_token: {
    title: "Complex Token & Incentive",
    description: "",
    hours: 100,
    hourly: 100,
    min_timeline: 7,
    max_timeline: 0,
    active: false,
  },
  token_simulation: {
    title: "Tokenomics Simulation",
    description: "",
    hours: 50,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 5,
    active: false,
  },
  go_to_market: {
    title: "Go-to-market strategy",
    description: "",
    hours: 30,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 5,
    active: false,
  },
  business_model: {
    title: "Business model, sustainability, or value capture strategy",
    description: "",
    hours: 40,
    hourly: 100,
    min_timeline: 4,
    max_timeline: 0,
    active: false,
  },
};

export default specificationOptions;
