-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."invoices" add column "created_at" time
--  not null default now();
