// v2.0.0

Table members {
  id uuid pk unique
  legacy_id text
  name text
  eth_address text
  is_raiding boolean
  primary_class_key text [ref: - guild_classes.guild_class]
  member_type_key text [ref: - member_types.member_type]
  championed_by_id uuid [ref: - members.id]
  application_id uuid [ref: - applications.id]
  membership_date datetime
  created_at datetime
  updated_at datetime
}

Table applications {
  id uuid pk unique
  name text
  eth_address text
  introduction text
  learning_goals text
  passion text
  favorite_media text
  crypto_thrills text
  why_raidguild text
  crypto_experience text
  comments text
  technical_skill_type_key text [ref: - technical_skill_types.technical_skill_type]
  dao_familiarity_key text [ref: - dao_familiarities.dao_familiarity]
  availability_key text [ref: - cohort_availabilities.cohort_availability]
  handbook_read boolean
  pledge_readiness boolean
  referred_by_id uuid [ref: - members.id]
  created_at datetime
}

Table raids {
  id uuid pk unique
  name text
  status_key text [ref: - raid_statuses.raid_status]
  category_key text [ref: - raid_categories.raid_category]
  cleric_id uuid [ref: - members.id]
  consultation_id uuid [ref: - consultations.id]
  portfolio_id uuid [ref: - portfolios.id]
  invoice_address text
  airtable_id text
  escrow_index int
  locker_hash text
  start_date datetime
  end_date datetime
  created_at datetime
  updated_at datetime
}

Table contact_infos {
  id uuid pk unique
  member_id uuid [ref: - members.id]
  application_id uuid [ref: - applications.id]
  client_id uuid [ref: - clients.id]
  email text UNIQUE
  discord text UNIQUE
  telegram text UNIQUE
  twitter text UNIQUE
  github text UNIQUE
}

Table clients {
  id uuid pk unique
  name text
  website text
}

Table contacts {
  id uuid pk unique
  name text
  bio text
  eth_address text
}

Table consultations {
  id uuid pk unique
  status_key text [ref: - consultation_statuses.consultation_status]
  client_id uuid [ref: - clients.id]
  name text
  link text
  description text
  type_key text [ref: - project_types.project_type]
  specs_key text [ref: - available_project_specs.available_project_spec]
  budget_key text [ref: - budget_options.budget_option]
  delivery_priorities_key text [ref: - delivery_priorities.delivery_priority]
  submission_type_key text [ref: - submission_types.submission_type]
  additional_info text
  submission_hash text
  consultation_hash text
  desired_delivery_date datetime
  created_at datetime
  updated_at datetime
}

Table portfolios {
  id uuid pk unique
  name text
  description text
  challenge text
  approach text
  result text
  category text [ref: - raid_categories.raid_category]
  case_study boolean
  repo_link text
  result_link text
  raid_id uuid [ref: - raids.id]
  created_at datetime
  updated_at datetime
}

Table comments {
  id uuid pk unique
  comment text
  member_id uuid [ref: - members.id]
  raid_id uuid [ref: - raids.id]
  reply_to_id uuid [ref: - comments.id]
  created_at datetime
  updated_at datetime
}

Table blogs {
  id uuid pk unique
  title text
  slug text
  author text
  image text
  description text
  content text
  tags jsonb
  created_at datetime
  updated_at datetime
}

// MANY-TO-MANY TABLES

Table raid_parties {
  id text pk unique
  raid_id text [ref: - raids.id]
  member_id text [ref: - members.id]
}

Table applications_skills {
  id uuid pk unique
  application_id uuid [ref: - applications.id]
  skill text [ref: - skills.skill]
  skill_type text [ref: - skill_types.skill_type]
}

Table members_skills {
  id uuid pk unique
  member_id uuid [ref: - members.id]
  skill text [ref: - skills.skill]
  skill_type text [ref: - skill_types.skill_type]
}

Table consultations_services_required {
  id uuid pk unique 
  consultation_id uuid [ref: - consultations.id]
  guild_service_key text [ref: - guild_services.guild_service]
}

Table clients_contacts {
  id uuid pk unique
  client_id uuid [ref: - clients.id]
  contact_id uuid [ref: - contacts.id]
}

Table consultations_contacts {
  id uuid pk unique
  consultation_id uuid [ref: - consultations.id]
  contact_id uuid [ref: - contacts.id]
}

Table portfolio_roles {
  id uuid pk unique
  portfolio_id uuid [ref: - portfolios.id]
  member_id uuid [ref: - members.id]
  role text [ref: - guild_classes.guild_class]
}

Table raids_roles_required {
  id uuid pk unique
  raid_id uuid [ref: - raids.id]
  role_required text [ref: - guild_classes.guild_class]
}

// ENUM TABLES

Table guild_classes {
  guild_class guild_classes
}

Table skills {
  skill skills
}

Table guild_services {
  guild_service guild_services
}

Table skill_types {
  skill_type skill_types
}

Table technical_skill_types {
  technical_skill_type technical_skill_types
}

Table dao_familiarities {
  dao_familiarity dao_familiarities
}

Table member_types {
  member_type member_types
}

Table project_types {
  project_type project_types
}

Table available_project_specs {
  available_project_spec available_project_specs
}

Table budget_options {
  budget_option budget_options
}

Table submission_types {
  submission_type submission_types
}

Table delivery_priorities {
  delivery_priority delivery_priorities
}

Table cohort_availabilities {
  cohort_availability cohort_availabilities
}

Table raid_statuses {
  raid_status raid_statuses
}

Table raid_categories {
  raid_category raid_categories
}

Table consultation_statuses {
  consultation_status consultation_statuses 
}

// HASURA ENUMS ARE ALL CAPS WITH UNDERSCORES

enum guild_classes {
  COMMUNITY
  DESIGN
  TREASURY
  MARKETING
  FRONTEND_DEV
  OPERATIONS
  BIZ_DEV
  BACKEND_DEV
  PROJECT_MANAGEMENT
  SMART_CONTRACTS
  LEGAL
  ACCOUNT_MANAGER
}

enum skills {
  FRONTEND
  BACKEND
  SOLIDITY
  BIZ_DEV
  COMMUNITY
  PROJECT_MANAGEMENT
  FINANCE
  PRODUCT_DESIGN
  UX_RESEARCH
  GAME_THEORY
  DEVOPS
  TOKENOMICS
  CONTENT
  MEMES
  VISUAL_DESIGN
  UI_DESIGN
  ILLUSTRATION
  LEGAL
  ACCOUNTING
}

enum guild_services {
  DAO
  DEVELOPMENT
  MARKETING
  MOTION_DESIGN
  NFTS
  SMART_CONTRACTS
  STRATEGY
  TOKENOMICS
  UX
  UI
  VISUAL_DESIGN
  HELP_ME
}

enum skill_types {
  PRIMARY
  SECONDARY
}

enum technical_skill_types {
  NOT_APPLICABLE
  TECHNICAL
  NON_TECHNICAL
  OTHER
}

enum dao_familiarities {
  NOT_APPLICABLE
  EXPERT
  FAMILIAR
  AWARE
  NONE
}

enum member_types {
  MEMBER
  APPRENTICE
  COHORT
}

enum project_types {
  NEW
  EXISTING
}

enum available_project_specs {
  YES
  PARTIAL
  NONE
}

enum budget_options {
  LESS_THAN_FIVE_THOUSAND
  FIVE_TO_TWENTY_THOUSAND
  TWENTY_TO_FIFTY_THOUSAND
  MORE_THAN_FIFTY_THOUSAND
  NOT_SURE
}

enum submission_types {
  PAID
  UNPAID
}

enum delivery_priorities {
  FAST_AND_POLISHED
  FAST_AND_INEXPENSIVE
  POLISHED_AND_INEXPENSIVE
}

enum cohort_availabilities {
  NOT_APPLICABLE
  LESS_THAN_FIVE_HOURS
  SIX_TO_TWELVE_HOURS
  THIRTEEN_TO_THIRTY_FIVE_HOURS
  MORE_THAN_THIRTY_SIX_HOURS
}

enum raid_statuses {
  AWAITING
  PREPARING
  RAIDING
  SHIPPED
  LOST
}

enum raid_categories {
  DESIGN_SPRINT
  FULL_STACK
  SMART_CONTRACTS
  BACKEND
  FRONTEND
  MARKETING
}

enum consultation_statuses {
  PENDING
  CANCELLED
  ACCEPTED
}
