CREATE TABLE "public"."consultations" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "v1_id" text,
  "name" text NOT NULL,
  "link" text NOT NULL,
  "type_key" text NOT NULL,
  "specs_key" text NOT NULL,
  "description" text,
  "desired_delivery_date" date,
  "budget_key" text NOT NULL,
  "delivery_priorities_key" text NOT NULL,
  "additional_info" text,
  "submission_type_key" text NOT NULL,
  "submission_hash" text,
  "consultation_hash" text,
  "consultation_status_key" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id") ,
  FOREIGN KEY ("type_key") REFERENCES "public"."project_types"("project_type") ON UPDATE restrict ON DELETE restrict,
  FOREIGN KEY ("specs_key") REFERENCES "public"."available_project_specs"("available_project_spec") ON UPDATE restrict ON DELETE restrict,
  FOREIGN KEY ("delivery_priorities_key") REFERENCES "public"."delivery_priorities"("delivery_priority") ON UPDATE restrict ON DELETE restrict,
  FOREIGN KEY ("budget_key") REFERENCES "public"."budget_options"("budget_option") ON UPDATE restrict ON DELETE restrict,
  FOREIGN KEY ("consultation_status_key") REFERENCES "public"."consultation_statuses"("consultation_status") ON UPDATE restrict ON DELETE restrict,
  FOREIGN KEY ("submission_type_key") REFERENCES "public"."submission_types"("submission_type") ON UPDATE restrict ON DELETE restrict,
  UNIQUE ("id")
);
CREATE EXTENSION IF NOT EXISTS pgcrypto;
