table:
  schema: public
  name: applications
object_relationships:
  - name: cohort_availability
    using:
      foreign_key_constraint_on: availability_key
  - name: dao_familiarity
    using:
      foreign_key_constraint_on: dao_familiarity_key
  - name: member
    using:
      foreign_key_constraint_on: referred_by_id
  - name: technical_skill_type
    using:
      foreign_key_constraint_on: technical_skill_type_key
array_relationships:
  - name: applications_skills
    using:
      foreign_key_constraint_on:
        column: application_id
        table:
          schema: public
          name: applications_skills
  - name: contact_infos
    using:
      foreign_key_constraint_on:
        column: application_id
        table:
          schema: public
          name: contact_infos
  - name: members
    using:
      foreign_key_constraint_on:
        column: application_id
        table:
          schema: public
          name: members
