table:
  schema: public
  name: applications
object_relationships:
  - name: cohort_availability
    using:
      foreign_key_constraint_on: availability
  - name: daoFamiliarityByDaoFamiliarity
    using:
      foreign_key_constraint_on: dao_familiarity
  - name: referredByMember
    using:
      foreign_key_constraint_on: referred_by
  - name: technical_skill_type
    using:
      foreign_key_constraint_on: skill_type
array_relationships:
  - name: member
    using:
      foreign_key_constraint_on:
        column: application
        table:
          schema: public
          name: members
  - name: skills
    using:
      foreign_key_constraint_on:
        column: application
        table:
          schema: public
          name: applications_skills
select_permissions:
  - role: member
    permission:
      columns:
        - handbook_read
        - pledge_readiness
        - availability
        - comments
        - crypto_experience
        - crypto_thrills
        - dao_familiarity
        - discord_handle
        - email_address
        - ens_name
        - eth_address
        - favorite_media
        - github_handle
        - introduction
        - learning_goals
        - name
        - passion
        - skill_type
        - telegram_handle
        - twitter_handle
        - v1_id
        - why_raidguild
        - created_at
        - updated_at
        - id
        - referred_by
      filter: {}
