table:
  schema: public
  name: applications_skills
object_relationships:
  - name: application
    using:
      foreign_key_constraint_on: application_id
  - name: skill
    using:
      foreign_key_constraint_on: skill_key
  - name: skill_type
    using:
      foreign_key_constraint_on: skill_type_key
