table:
  name: applications_skills
  schema: public
object_relationships:
  - name: application
    using:
      foreign_key_constraint_on: application_id
  - name: skill
    using:
      foreign_key_constraint_on: skill_key
  - name: skill_type
    using:
      foreign_key_constraint_on: skill_type_key
insert_permissions:
  - role: member
    permission:
      check: {}
      columns:
        - skill_key
        - skill_type_key
        - application_id
        - id
select_permissions:
  - role: member
    permission:
      columns:
        - id
        - application_id
        - skill_key
        - skill_type_key
      filter: {}
update_permissions:
  - role: member
    permission:
      columns:
        - skill_key
        - skill_type_key
        - application_id
        - id
      filter: {}
      check: null
