table:
  schema: public
  name: applications
object_relationships:
  - name: cohort_availability
    using:
      foreign_key_constraint_on: availability
  - name: daoFamiliarityByDaoFamiliarity
    using:
      foreign_key_constraint_on: dao_familiarity
  - name: member
    using:
      foreign_key_constraint_on: referred_by
  - name: technical_skill_type
    using:
      foreign_key_constraint_on: skill_type
array_relationships:
  - name: applications_skills
    using:
      foreign_key_constraint_on:
        column: application
        table:
          schema: public
          name: applications_skills
  - name: members
    using:
      foreign_key_constraint_on:
        column: application
        table:
          schema: public
          name: members
select_permissions:
  - role: user
    permission:
      columns:
        - ens_name
        - eth_address
        - why_raidguild
      filter: {}
